CREATE TABLE IF NOT EXISTS volunteer_applications (
  id UUID PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  address TEXT NOT NULL,
  postcode TEXT NOT NULL,
  phone TEXT NOT NULL,
  emergency_name TEXT NOT NULL,
  emergency_phone TEXT NOT NULL,
  role TEXT NOT NULL,
  availability TEXT NOT NULL,
  experience TEXT,
  support_needs TEXT,
  why_work_here TEXT,
  how_did_you_find_out TEXT,
  nationality_visa TEXT,
  food_hygiene_certificate TEXT,
  food_hygiene_certificate_bring TEXT,
  referee1_name TEXT,
  referee1_address TEXT,
  referee1_postcode TEXT,
  referee1_email TEXT,
  referee1_phone TEXT,
  referee1_relationship TEXT,
  referee2_name TEXT,
  referee2_address TEXT,
  referee2_postcode TEXT,
  referee2_email TEXT,
  referee2_phone TEXT,
  referee2_relationship TEXT,
  signature TEXT,
  signature_date DATE,
  referee_name TEXT,
  referee_email TEXT,
  referee_relationship TEXT,
  reference_requested_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);